
COCO_MAP = {    0: b'/noose',
                1: b'/neck',
                2: b'/shoulder_R',
                3: b'/elbow_R',
                4: b'/wrist_R',
                5: b'/shoulder_L',
                6: b'/elbow_L',
                7: b'/wrist_L',
                8: b'/hip_R',
                9: b'/knee_R',
                10: b'/ankle_R',
                11: b'/hip_L',
                12: b'/knee_L',
                13: b'/ankle_L',
                14: b'/eye_R',
                15: b'/eye_L',
                16: b'/ear_R',
                17: b'/ear_L' }

MPI_MAP = { 0: b'/head',
            1: b'/neck',
            2: b'/shoulder_R',
            3: b'/elbow_R',
            4: b'/wrist_R',
            5: b'/shoulder_L',
            6: b'/elbow_L',
            7: b'/wrist_L',
            8: b'/hip_R',
            9: b'/knee_R',
            10: b'/ankle_R',
            11: b'/hip_L',
            12: b'/knee_L',
            13: b'/ankle_L',
            14: b'/chest'}
